import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="Ferret Rescue Webpage" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      {/*Image goes in the main Container with CSS */}
      <section className={styles.mainContainer}>
        <h1 className={styles.someText}>Ferret Shelter</h1>
      </section>
      <section className={styles.infoContainer}>
        <div className={styles.textContainer}>
          <h2>About Us</h2>
          <p className={styles.para}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed delectus laudantium doloribus impedit debitis facilis unde animi quod illum iste!</p>
          <p className={styles.para}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed delectus laudantium doloribus impedit debitis facilis unde animi quod illum iste!</p>
          <p className={styles.para}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed delectus laudantium doloribus impedit debitis facilis unde animi quod illum iste!</p>
        </div>
        <div className={styles.imgContainer}>
          <img className={styles.img} src={'/ferret-home.jpg'} />
        </div>
      </section>
    </>
  )
}
